version: "3.9"

services:
    tfc:
        container_name: noto-emoji-example-app
        image: noto-emoji-example-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8811"
